package org.gatein.wcm.performance;

public class WcmResources {

    public static final String HTML_ES = "<h1>Primer test...</h1>" +
            "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc odio arcu, sollicitudin ut volutpat ac, placerat nec quam. Suspendisse ut massa sed lorem placerat eleifend. In ut feugiat orci. Ut faucibus urna ut ante malesuada sodales. Integer vel nunc eget justo sagittis faucibus. Duis congue augue quis est interdum scelerisque. Nunc hendrerit fringilla pellentesque. Quisque pellentesque euismod purus vitae cursus.</p>" +
            "<p>Mauris aliquam, urna in facilisis aliquam, leo metus fermentum est, in ullamcorper purus ligula eu massa. Nam aliquet dapibus sem, sed ornare felis tempus vitae. Pellentesque lorem leo, dignissim nec lobortis et, cursus non mauris. Morbi elementum mauris eget justo bibendum ultrices. Vestibulum quis ligula molestie libero scelerisque tincidunt. Vivamus quis ipsum nec lacus convallis vestibulum at ac neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla porta tellus vel dui tempor id hendrerit ante placerat. Ut ac enim dui, eget sollicitudin magna. Ut nunc dui, consectetur vitae aliquam a, pulvinar eu felis. Suspendisse augue dolor, tincidunt non tincidunt varius, feugiat quis mauris. Integer a ante at nisl tincidunt sodales vel vitae purus. In ut libero fermentum nunc iaculis vulputate a id ipsum. Suspendisse fermentum nulla id nunc vehicula ut gravida dolor vulputate. Proin venenatis consectetur pretium.</p>" +
            "<p>Duis varius tincidunt nisl quis consequat. Duis non posuere massa. Nam odio lorem, lobortis ut lacinia nec, pellentesque in quam. Curabitur et auctor magna. Curabitur viverra mollis lectus at fringilla. Curabitur vulputate lobortis faucibus. Proin at lacinia augue. Aliquam erat volutpat. Vivamus suscipit dictum dolor, at elementum nulla faucibus vel. Vestibulum condimentum, enim vel aliquam tincidunt, arcu lacus vulputate libero, at placerat sem tellus viverra lorem. Vestibulum tristique augue at sem convallis adipiscing. Pellentesque eleifend est nec odio interdum vel facilisis metus luctus. In a velit et metus commodo condimentum vitae non ligula. Ut vitae turpis quam, sed euismod elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus nisi turpis, iaculis vitae pellentesque et, ultrices ut risus.</p>" +
            "<p>Maecenas semper mattis nisl sit amet blandit. Donec mattis fringilla risus, sit amet elementum ipsum mattis at. Vivamus quis lorem nibh. Nullam consectetur tellus at quam feugiat rutrum dignissim sed odio. Suspendisse potenti. Maecenas pharetra egestas luctus. Morbi viverra eros vitae sem laoreet sed pretium urna venenatis. Proin vulputate lectus sed risus ullamcorper lacinia.</p>" +
            "<p>Donec est felis, egestas tempor consectetur vel, volutpat in elit. Praesent ante justo, interdum eget dignissim eu, luctus eu orci. Donec egestas nulla id nisi pellentesque sagittis. Fusce vitae eros quam. Aliquam erat volutpat. Nam non arcu ultricies lectus commodo ullamcorper. Cras suscipit erat vitae orci dictum vitae rhoncus velit gravida. Aliquam nunc leo, rhoncus sit amet vehicula vel, eleifend eu tellus. Mauris at justo nunc. Ut ultricies posuere velit a dignissim. Suspendisse ac eros tellus, sit amet aliquet nisl.</p>";

    public static final String HTML_EN = "<h1>First test...</h1>" +
            "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc odio arcu, sollicitudin ut volutpat ac, placerat nec quam. Suspendisse ut massa sed lorem placerat eleifend. In ut feugiat orci. Ut faucibus urna ut ante malesuada sodales. Integer vel nunc eget justo sagittis faucibus. Duis congue augue quis est interdum scelerisque. Nunc hendrerit fringilla pellentesque. Quisque pellentesque euismod purus vitae cursus.</p>" +
            "<p>Mauris aliquam, urna in facilisis aliquam, leo metus fermentum est, in ullamcorper purus ligula eu massa. Nam aliquet dapibus sem, sed ornare felis tempus vitae. Pellentesque lorem leo, dignissim nec lobortis et, cursus non mauris. Morbi elementum mauris eget justo bibendum ultrices. Vestibulum quis ligula molestie libero scelerisque tincidunt. Vivamus quis ipsum nec lacus convallis vestibulum at ac neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla porta tellus vel dui tempor id hendrerit ante placerat. Ut ac enim dui, eget sollicitudin magna. Ut nunc dui, consectetur vitae aliquam a, pulvinar eu felis. Suspendisse augue dolor, tincidunt non tincidunt varius, feugiat quis mauris. Integer a ante at nisl tincidunt sodales vel vitae purus. In ut libero fermentum nunc iaculis vulputate a id ipsum. Suspendisse fermentum nulla id nunc vehicula ut gravida dolor vulputate. Proin venenatis consectetur pretium.</p>" +
            "<p>Duis varius tincidunt nisl quis consequat. Duis non posuere massa. Nam odio lorem, lobortis ut lacinia nec, pellentesque in quam. Curabitur et auctor magna. Curabitur viverra mollis lectus at fringilla. Curabitur vulputate lobortis faucibus. Proin at lacinia augue. Aliquam erat volutpat. Vivamus suscipit dictum dolor, at elementum nulla faucibus vel. Vestibulum condimentum, enim vel aliquam tincidunt, arcu lacus vulputate libero, at placerat sem tellus viverra lorem. Vestibulum tristique augue at sem convallis adipiscing. Pellentesque eleifend est nec odio interdum vel facilisis metus luctus. In a velit et metus commodo condimentum vitae non ligula. Ut vitae turpis quam, sed euismod elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus nisi turpis, iaculis vitae pellentesque et, ultrices ut risus.</p>" +
            "<p>Maecenas semper mattis nisl sit amet blandit. Donec mattis fringilla risus, sit amet elementum ipsum mattis at. Vivamus quis lorem nibh. Nullam consectetur tellus at quam feugiat rutrum dignissim sed odio. Suspendisse potenti. Maecenas pharetra egestas luctus. Morbi viverra eros vitae sem laoreet sed pretium urna venenatis. Proin vulputate lectus sed risus ullamcorper lacinia.</p>" +
            "<p>Donec est felis, egestas tempor consectetur vel, volutpat in elit. Praesent ante justo, interdum eget dignissim eu, luctus eu orci. Donec egestas nulla id nisi pellentesque sagittis. Fusce vitae eros quam. Aliquam erat volutpat. Nam non arcu ultricies lectus commodo ullamcorper. Cras suscipit erat vitae orci dictum vitae rhoncus velit gravida. Aliquam nunc leo, rhoncus sit amet vehicula vel, eleifend eu tellus. Mauris at justo nunc. Ut ultricies posuere velit a dignissim. Suspendisse ac eros tellus, sit amet aliquet nisl.</p>";

    public static final String HTML_FR = "<h1>Premiers tests...</h1>" +
            "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc odio arcu, sollicitudin ut volutpat ac, placerat nec quam. Suspendisse ut massa sed lorem placerat eleifend. In ut feugiat orci. Ut faucibus urna ut ante malesuada sodales. Integer vel nunc eget justo sagittis faucibus. Duis congue augue quis est interdum scelerisque. Nunc hendrerit fringilla pellentesque. Quisque pellentesque euismod purus vitae cursus.</p>" +
            "<p>Mauris aliquam, urna in facilisis aliquam, leo metus fermentum est, in ullamcorper purus ligula eu massa. Nam aliquet dapibus sem, sed ornare felis tempus vitae. Pellentesque lorem leo, dignissim nec lobortis et, cursus non mauris. Morbi elementum mauris eget justo bibendum ultrices. Vestibulum quis ligula molestie libero scelerisque tincidunt. Vivamus quis ipsum nec lacus convallis vestibulum at ac neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla porta tellus vel dui tempor id hendrerit ante placerat. Ut ac enim dui, eget sollicitudin magna. Ut nunc dui, consectetur vitae aliquam a, pulvinar eu felis. Suspendisse augue dolor, tincidunt non tincidunt varius, feugiat quis mauris. Integer a ante at nisl tincidunt sodales vel vitae purus. In ut libero fermentum nunc iaculis vulputate a id ipsum. Suspendisse fermentum nulla id nunc vehicula ut gravida dolor vulputate. Proin venenatis consectetur pretium.</p>" +
            "<p>Duis varius tincidunt nisl quis consequat. Duis non posuere massa. Nam odio lorem, lobortis ut lacinia nec, pellentesque in quam. Curabitur et auctor magna. Curabitur viverra mollis lectus at fringilla. Curabitur vulputate lobortis faucibus. Proin at lacinia augue. Aliquam erat volutpat. Vivamus suscipit dictum dolor, at elementum nulla faucibus vel. Vestibulum condimentum, enim vel aliquam tincidunt, arcu lacus vulputate libero, at placerat sem tellus viverra lorem. Vestibulum tristique augue at sem convallis adipiscing. Pellentesque eleifend est nec odio interdum vel facilisis metus luctus. In a velit et metus commodo condimentum vitae non ligula. Ut vitae turpis quam, sed euismod elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus nisi turpis, iaculis vitae pellentesque et, ultrices ut risus.</p>" +
            "<p>Maecenas semper mattis nisl sit amet blandit. Donec mattis fringilla risus, sit amet elementum ipsum mattis at. Vivamus quis lorem nibh. Nullam consectetur tellus at quam feugiat rutrum dignissim sed odio. Suspendisse potenti. Maecenas pharetra egestas luctus. Morbi viverra eros vitae sem laoreet sed pretium urna venenatis. Proin vulputate lectus sed risus ullamcorper lacinia.</p>" +
            "<p>Donec est felis, egestas tempor consectetur vel, volutpat in elit. Praesent ante justo, interdum eget dignissim eu, luctus eu orci. Donec egestas nulla id nisi pellentesque sagittis. Fusce vitae eros quam. Aliquam erat volutpat. Nam non arcu ultricies lectus commodo ullamcorper. Cras suscipit erat vitae orci dictum vitae rhoncus velit gravida. Aliquam nunc leo, rhoncus sit amet vehicula vel, eleifend eu tellus. Mauris at justo nunc. Ut ultricies posuere velit a dignissim. Suspendisse ac eros tellus, sit amet aliquet nisl.</p>";

    public static final String HTML_DE = "<h1>Erste Tests...</h1>" +
            "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc odio arcu, sollicitudin ut volutpat ac, placerat nec quam. Suspendisse ut massa sed lorem placerat eleifend. In ut feugiat orci. Ut faucibus urna ut ante malesuada sodales. Integer vel nunc eget justo sagittis faucibus. Duis congue augue quis est interdum scelerisque. Nunc hendrerit fringilla pellentesque. Quisque pellentesque euismod purus vitae cursus.</p>" +
            "<p>Mauris aliquam, urna in facilisis aliquam, leo metus fermentum est, in ullamcorper purus ligula eu massa. Nam aliquet dapibus sem, sed ornare felis tempus vitae. Pellentesque lorem leo, dignissim nec lobortis et, cursus non mauris. Morbi elementum mauris eget justo bibendum ultrices. Vestibulum quis ligula molestie libero scelerisque tincidunt. Vivamus quis ipsum nec lacus convallis vestibulum at ac neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla porta tellus vel dui tempor id hendrerit ante placerat. Ut ac enim dui, eget sollicitudin magna. Ut nunc dui, consectetur vitae aliquam a, pulvinar eu felis. Suspendisse augue dolor, tincidunt non tincidunt varius, feugiat quis mauris. Integer a ante at nisl tincidunt sodales vel vitae purus. In ut libero fermentum nunc iaculis vulputate a id ipsum. Suspendisse fermentum nulla id nunc vehicula ut gravida dolor vulputate. Proin venenatis consectetur pretium.</p>" +
            "<p>Duis varius tincidunt nisl quis consequat. Duis non posuere massa. Nam odio lorem, lobortis ut lacinia nec, pellentesque in quam. Curabitur et auctor magna. Curabitur viverra mollis lectus at fringilla. Curabitur vulputate lobortis faucibus. Proin at lacinia augue. Aliquam erat volutpat. Vivamus suscipit dictum dolor, at elementum nulla faucibus vel. Vestibulum condimentum, enim vel aliquam tincidunt, arcu lacus vulputate libero, at placerat sem tellus viverra lorem. Vestibulum tristique augue at sem convallis adipiscing. Pellentesque eleifend est nec odio interdum vel facilisis metus luctus. In a velit et metus commodo condimentum vitae non ligula. Ut vitae turpis quam, sed euismod elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus nisi turpis, iaculis vitae pellentesque et, ultrices ut risus.</p>" +
            "<p>Maecenas semper mattis nisl sit amet blandit. Donec mattis fringilla risus, sit amet elementum ipsum mattis at. Vivamus quis lorem nibh. Nullam consectetur tellus at quam feugiat rutrum dignissim sed odio. Suspendisse potenti. Maecenas pharetra egestas luctus. Morbi viverra eros vitae sem laoreet sed pretium urna venenatis. Proin vulputate lectus sed risus ullamcorper lacinia.</p>" +
            "<p>Donec est felis, egestas tempor consectetur vel, volutpat in elit. Praesent ante justo, interdum eget dignissim eu, luctus eu orci. Donec egestas nulla id nisi pellentesque sagittis. Fusce vitae eros quam. Aliquam erat volutpat. Nam non arcu ultricies lectus commodo ullamcorper. Cras suscipit erat vitae orci dictum vitae rhoncus velit gravida. Aliquam nunc leo, rhoncus sit amet vehicula vel, eleifend eu tellus. Mauris at justo nunc. Ut ultricies posuere velit a dignissim. Suspendisse ac eros tellus, sit amet aliquet nisl.</p>";

}
